# Generated by Django 3.0.8 on 2020-11-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='trans',
        ),
    ]
