# Generated by Django 3.0.8 on 2020-11-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_patient_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='doctors',
        ),
    ]
