# Generated by Django 3.0.8 on 2020-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_resource_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condi',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=64),
        ),
    ]
